<?php

/**
 * @file
 * bitcoin_daily_exchange_rate.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function bitcoin_daily_exchange_rate_field_default_field_instances(): array {
  $field_instances = array();

  // Exported field_instance: 'node-bitcoin_daily-body'.
  $field_instances['node-bitcoin_daily-body'] = array(
    'bundle' => 'bitcoin_daily',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => -4,
    ),
  );

  // Exported field_instance: 'node-bitcoin_daily-field_bitcoin_usd_rate'.
  $field_instances['node-bitcoin_daily-field_bitcoin_usd_rate'] = array(
    'bundle' => 'bitcoin_daily',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_bitcoin_usd_rate',
    'label' => 'Todays Bitcoin Rate in USD',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => -3,
    ),
  );

  // Translatables.
  t('Body');
  t('Todays Bitcoin Rate in USD');

  return $field_instances;
}
